--- 
abstract: render parts of your mail with Template-Toolkit
author: 
  - Ricardo SIGNES <rjbs@cpan.org>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.003
license: perl
name: Email-MIME-Kit-Renderer-TT
requires: 
  Email::MIME::Kit: 2
  Template: 2
version: 0.001
